'use client';
import { useState } from 'react';
import { Bike, Check, CreditCard, MapPin, Package, ReceiptText } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useData } from './data-provider';
import { money, nextStatus } from '@/lib/domain';
import { Status } from './shared';
export function OrderDetail({ id, close }: { id: string | null; close: () => void }) {
  const { state, execute, busy } = useData(); const [riderId, setRiderId] = useState('');
  const order = state?.orders.find(o => o.id === id); const restaurant = state?.restaurants.find(r => r.id === order?.restaurantId);
  return <Dialog open={!!order} onOpenChange={open => { if (!open) { setRiderId(''); close(); } }}><DialogContent className="detail-dialog"><DialogHeader><div className="eyebrow">ORDER DETAILS</div><DialogTitle>{order?.id}</DialogTitle><DialogDescription>{restaurant?.name} · {order?.customer}</DialogDescription></DialogHeader>{order && <><div className="detail-status"><Status value={order.status}/><strong>{money(order.amount)}</strong></div><div className="detail-section"><h3><Package size={17}/>Items</h3><p>{order.items}</p></div><div className="detail-section"><h3><MapPin size={17}/>Delivery address</h3><p>{order.address}</p></div><div className="detail-section"><h3><CreditCard size={17}/>Payment</h3><p>{order.paid ? 'Verified card payment via BML' : 'Awaiting verification'}</p><small>{order.paymentRef}</small></div><div className="detail-section"><h3><Bike size={17}/>Delivery partner</h3><p>{state?.riders.find(r => r.id === order.riderId)?.name ?? 'No rider assigned yet'}</p>{!['Delivered', 'On the way', 'Needs attention'].includes(order.status) && <div className="inline-controls"><Select value={riderId} onValueChange={v => { if (v !== null) setRiderId(v); }}><SelectTrigger className="flex-1"><SelectValue placeholder="Choose an available rider">{state?.riders.find(r => r.id === riderId)?.name}</SelectValue></SelectTrigger><SelectContent>{state?.riders.filter(r => r.status === 'Active' && r.online && !state.orders.some(o => o.riderId === r.id && o.status !== 'Delivered')).map(r => <SelectItem key={r.id} value={r.id}>{r.name}</SelectItem>)}</SelectContent></Select><Button disabled={!riderId || busy} variant="outline" onClick={async () => { if (await execute({ type: 'assign-rider', id: order.id, riderId })) setRiderId(''); }}>Assign</Button></div>}</div><p className="policy-note"><ReceiptText size={16}/>Paid orders cannot be cancelled by customers. Order problems are handled through support.</p>{nextStatus[order.status] && <Button disabled={busy} className="w-full" onClick={() => execute({ type: 'order-status', id: order.id, status: nextStatus[order.status]! })}><Check size={16}/>Mark {nextStatus[order.status]?.toLowerCase()}</Button>}</>}</DialogContent></Dialog>;
}
