name: igo_mobile
description: iGO customer, restaurant and rider application.
publish_to: none
version: 0.1.0+1
environment:
  sdk: ^3.13.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  maplibre_gl: ^0.27.1
  clerk_flutter: 0.0.18-beta
  clerk_auth: 0.0.18-beta
  flutter_secure_storage: ^11.2.0
  http: ^1.6.0
  url_launcher: ^6.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/brand/igo-logo.jpg
